Mpdz2 649 e mail notification
it-at-m/zammad-ldap-sync pull request #44
Opened 2024-09-19 08:36 UTC by sfi2022

**Description**

- LDAP-Sync EMail notification in case of invalid distinguished name.
- Test support extended.

**Reference**
Issues MPDZ2-649:

2024-09-30 06:32 UTC, markostreich requested changes
Die Testabdeckung hat sich wesentlich verbessert, was sehr gut ist. Bei den Tests würde ich jeweils noch ein, zwei Hinweise zum Testziel hinzufügen, weil es durch die Verwendung des ArgumentCaptor etwas schwer verständlich ist. Das so gemockt werden muss, sehe ich aber auch.

Die anderen Kleinigkeiten sollten noch ausgebessert werden.

2024-09-30 06:32 UTC, markostreich commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +	protected  Map<String, LdapOuNode> createChildLdapTree() {
Wird nie verwendet. Falls es nicht noch zukünftig gebraucht wird, würde ich es löschen.

2024-09-30 11:22 UTC, sfi2022 commented on pom.xml
✅

2024-09-30 11:22 UTC, sfi2022 commented on pom.xml
> +		</dependency>
✅

2024-09-30 11:24 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/Validation.java
> +				sb.append(System.lineSeparator() + System.lineSeparator());
✅

2024-09-30 11:24 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/Validation.java
> +import java.util.stream.Collectors;
✅

2024-09-30 11:44 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/Validation.java
> +		}
✅ Yes you are right.

2024-09-30 11:50 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncService.java
> +        log.info("Zammad role ids found : {} .", roleProperty.toString());
✅

2024-09-30 11:53 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadUserDTO>> zammadUsersByLhmObjectId;
Which one ?

2024-09-30 11:53 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadGroupDTO>> zammadGroupsByLhmObjectId;
Which one ?

2024-09-30 11:54 UTC, sfi2022 commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +        super();
✅

2024-09-30 11:57 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/CreateGroupAndUserTest.java
> +import static org.junit.Assert.assertEquals;
✅ Just clicked wrong insertion.

2024-09-30 11:59 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +	    var node = new LdapOuNode(dn, createEnhancedLdapOuSearchResultDTO(level,number), new TreeMap<String, LdapOuNode>(), createLdapOuUser(level, 2));
✅

2024-09-30 12:00 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +        nodes.put(dn,  new LdapOuNode(dn, createEnhancedLdapOuSearchResultDTO(level,number), new TreeMap<String, LdapOuNode>(), createLdapOuUser(level, 3)));
✅

2024-09-30 13:08 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +	protected List<ZammadUserDTO> zammdUsers() {
✅

2024-09-30 13:08 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +	protected List<ZammadGroupDTO> zammdGroups() {
✅

2024-09-30 13:16 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/CreateGroupAndUserTest.java
> +		var zammadSyncService = new ZammadSyncServiceSubtree(zammadService, createZammadProperties());
I think it should be clear because creation and use follows in two lines. But i changed it.

2024-09-30 13:19 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/CreateUpdateGroupAndUserTest.java
> +import static org.junit.Assert.assertEquals;
✅

2024-09-30 13:20 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/DeleteGroupAndUserTest.java
> +import static org.junit.Assert.assertEquals;
✅

2024-09-30 13:21 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +    protected ZammadUserDTO zamadUser_lhmobjectId_2_2_3_reset() {
✅

2024-09-30 13:26 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/PrepareTestEnvironment.java
> +	protected  Map<String, LdapOuNode> createChildLdapTree() {
✅

2024-09-30 13:31 UTC, sfi2022 commented on src/test/java/de/muenchen/zammad/ldap/service/DistinguishedNameEMailTest.java
> +import static org.junit.Assert.assertTrue;
✅

2024-09-30 14:30 UTC, markostreich commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadUserDTO>> zammadUsersByLhmObjectId;
![grafik](https://github.com/user-attachments/assets/b5c7a1d9-09ec-4fbb-ac45-c36f37a8212c)

`zammadUsersByLhmObjectId` itself

2024-09-30 14:31 UTC, markostreich commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadGroupDTO>> zammadGroupsByLhmObjectId;
`zammadGroupsByLhmObjectId` itself

2024-09-30 14:48 UTC, markostreich commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadUserDTO>> zammadUsersByLhmObjectId;
ok my fault

Its correct.

2024-09-30 14:49 UTC, markostreich commented on src/main/java/de/muenchen/zammad/ldap/service/ZammadSyncServiceSubtree.java
> +    Map<String, List<ZammadGroupDTO>> zammadGroupsByLhmObjectId;
ok my fault

Its correct.

2024-09-30 14:49 UTC, markostreich approved these changes

2024-10-08 07:29 UTC, markostreich approved these changes

2024-10-28 11:16 UTC, merged